### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jlcaldu** [thlee/SNPhylo#6]
Hi,

I am trying to run a .gds file, but I get the next message.

user@Samsung:~/SNPhylo$ ~/SNPhylo/snphylo.sh -H maiz_final.gds
Start to remove low quality data.
Traceback (most recent call last):
  File "/home/user/SNPhylo/scripts/remove_no_genotype_data.py", line 35, in <module>
    _ = int(snp_data[2])
IndexError: list index out of range

I don't know what my error is, I would appreciate any help.

Thanks

**Comment by lly1214** [comment]
I met the same error：

Start to remove low quality data.
Traceback (most recent call last):
  File "/public/home/casdao/kdylvfenghua/kdyluolingyun/soft/SNPhylo-20180901/scripts/remove_low_depth_genotype_data.py", line 73, in <module>
    if int(genotype_col[dp_col_no]) < min_depth: num_low_depth_sample += 1
IndexError: list index out of range

Have you resolved it? any solution?
